import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./NavBar";
import Footer from "./Footer";

export const metadata: Metadata = {
  title: "My eCommerce App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex flex-col min-h-screen">
          <main className="flex-1">
            <NavBar />
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
